Add Zuul as CI
terraform-opentelekomcloud-modules/terraform-opentelekomcloud-vpc pull request #2
Opened 2021-04-14 15:01 UTC by lego963

2021-04-14 15:04 UTC, lego963 commented
recheck

2021-04-20 09:39 UTC, outcatcher requested changes

2021-04-20 09:39 UTC, outcatcher commented on .editorconfig
> +max_line_length = 0
`max_line_length = 0` ― is this a valid value?

2021-04-20 09:39 UTC, outcatcher commented on .editorconfig
> +max_line_length = 80
Maybe use `100` for `max_line_length`?

2021-04-20 09:39 UTC, outcatcher commented on README.md
> +| <a name="input_dns_nameservers"></a> [dns\_nameservers](#input\_dns\_nameservers)       | An array of DNS name servers used by hosts in the subnet   | `list(string)` | <pre>[<br>  "100.125.4.25",<b
Maybe we should use `8.8.8.8` or `1.1.1.1` as an additional name server in case there are problems with internal ones.

2021-04-20 09:45 UTC, lego963 commented on .editorconfig
> +max_line_length = 0
removed

2021-04-20 09:45 UTC, lego963 commented on .editorconfig
> +max_line_length = 80
done

2021-04-20 09:45 UTC, lego963 commented on README.md
> +| <a name="input_dns_nameservers"></a> [dns\_nameservers](#input\_dns\_nameservers)       | An array of DNS name servers used by hosts in the subnet   | `list(string)` | <pre>[<br>  "100.125.4.25",<b
add 8.8.8.8

2021-04-20 09:46 UTC, outcatcher submitted a review, later dismissed

2021-04-20 09:55 UTC, outcatcher approved these changes

2021-04-20 10:06 UTC, lego963 commented
regate

2021-04-20 10:10 UTC, merged